version: "3.3"

services:
  frontend:
    image: catamo/venue-hotel-client
    build: venue-hotel-client/
    command: yarn start
    ports:
      - "3000:5000"
    environment:
      PORT: 5000
      HOST: 0.0.0.0
      SERVER_URL: http://172.25.0.10:4000
      NODE_ENV: production
    networks:
      appnet:
        ipv4_address: 172.25.0.11

  server:
    image: catamo/venue-hotel-api
    build: venue-hotel-api/
    command: yarn start
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      IMAGES_SERVER_URL: http://localhost:4000/static
    networks:
      appnet:
        ipv4_address: 172.25.0.10

networks:
  appnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
