version: "3.3"

services:
  frontend:
    image: catamo/venue-hotel-client
    build: venue-hotel-client/
    volumes:
      - ./venue-hotel-client:/usr/src/app
    command: yarn dev
    ports:
      - "3000:5000"
    environment:
      PORT: 5000
      HOST: 0.0.0.0
      API_URL: http://localhost:4000/

  server:
    image: catamo/venue-hotel-api
    build: venue-hotel-api/
    command: json-server --host 0.0.0.0 --port 4000 src/real-data.js
    ports:
      - "4000:4000"
    environment:
      PORT: 4000